tinyMCE.addI18n('my.advanced',{
style_select:"စတိုင်များ",
font_size:"ေဖာင့်စာလံုး အရွယ်",
fontdefault:"ေဖာင့်စာလံုး မိသားစု",
block:"ပံုစံချပံု",
paragraph:"စာပိုဒ်",
div:"Div",
address:"လိပ်စာ",
pre:"ြကိုတင်ပံုစံချထားေသာ",
h1:"ေခါင်းစဉ် ၁",
h2:"ေခါင်းစဉ် ၂",
h3:"ေခါင်းစဉ် ၃",
h4:"ေခါင်းစဉ် ၄",
h5:"ေခါင်းစဉ် ၅",
h6:"ေခါင်းစဉ် ၆",
blockquote:"ကိုးကားချက် စာပိုဒ်",
code:"ကုတ်",
samp:"ကုတ် နမူနာ",
dt:"အဓိပ္ပါယ် သတ်မှတ်ချက်စာလံုး ",
dd:"အဓိပ္ပါယ် ေဖာ်ြပချက်များ",
bold_desc:"စာလံုးအထူ (Ctrl+B)",
italic_desc:"စာလံုးေစာင်း (Ctrl+I)",
underline_desc:"ေအာက်မျဉ်း (Ctrl+U)",
striketrough_desc:"ြဖတ်မျဉ်း",
justifyleft_desc:"ဘယ်ညိှ",
justifycenter_desc:"အလယ်ညိှ",
justifyright_desc:"ညာညိှ",
justifyfull_desc:"အြပည့်ညိှ",
bullist_desc:"အစီအစဉ်မရှိေသာ စာရင်း",
numlist_desc:"အစီအစဉ်ချထားေသာ စာရင်း",
outdent_desc:"Outdent",
indent_desc:"Indent",
undo_desc:"မလုပ် (Ctrl+Z)",
redo_desc:"ြပန်လုပ် (Ctrl+Y)",
link_desc:"ချိတ်ဆက်လိပ်စာ ထည့်/ြပင်",
unlink_desc:"ချိတ်ဆက်လိပ်စာြဖုတ်",
image_desc:"ရုပ်ပံု ထည့်/ြပင်",
cleanup_desc:"ရှုပ်ပွေနေသာ ကုတ်များကို ရှင်း",
code_desc:"HTML ရင်းြမစ်ကို ြပုြပင်",
sub_desc:"Subscript",
sup_desc:"Superscript",
hr_desc:"ေရြပင်ညီ ေပတံထည့်သွင်း",
removeformat_desc:"ပံုစံချထားမှုများကို ဖယ်ရှား",
custom1_desc:"သင့်စိတ်ြကိုက် ေဖာ်ြပချက်ကို ဒီမှာြဖည့်ပါ",
forecolor_desc:"စာသား အေရာင်ေရွးပါ",
backcolor_desc:"ေနာက်ခံ အေရာင်ေရွးပါ",
charmap_desc:"စိတ်ြကိုက် အက္ခရာ ထည့်ပါ",
visualaid_desc:"Toggle guidelines/invisible elements",
anchor_desc:"ချိတ် ထည့်/ြပင်",
cut_desc:"ြဖတ်",
copy_desc:"မိတ္တူကူး",
paste_desc:"ြဖည့်ကူး",
image_props_desc:"ရုပ်ပံု ဝိေသသလက္ခဏာများ",
newdocument_desc:"စာရွက်စာတမ်း အသစ်",
help_desc:"အကူအညီ",
blockquote_desc:"ကိုးကားချက်စာပိုဒ်",
clipboard_msg:"Mozilla နှင့် Firefox တွင် မိတ္တူကူး/ြဖတ်/ြဖည့်ကူး မှုများ မြပုလုပ်နိုင်ပါ။\r\nဒီြပဿနာအေြကာင်း အေသးစိတ်ထပ်မံ သိလိုပါသလား?",
path:"လမ်းေြကာင်း",
newdocument:"ပါဝင်မှုများအားလံုးကို ဖယ်ရှာလိုသည်မှာ ေသချာရဲ့လား?",
toolbar_focus:"ကိရိယာခလုပ်များသို့သွားရန် - Alt+Q၊ စာသားြပုြပင်ရန်ေနရာသို့သွားရန် - Alt-Z၊ အစိတ်အပိုင်းလမ်းေြကာင်းသို့သွားရန် - Alt-X",
more_colors:"ေနာက်ထပ် အေရာင်များ"
});