tinyMCE.addI18n('my.advanced_dlg',{
about_title:"TinyMCE အေြကာင်း",
about_general:"သိေကာင်းစရာ",
about_help:"အကူအညီ",
about_license:"လိုင်စင်",
about_plugins:"ပလပ်အင်များ",
about_plugin:"ပလပ်အင်",
about_author:"ေရးသူ",
about_version:"ဗားရှင်း",
about_loaded:"လုပ်ေဆာင်ေနေသာ ပလပ်အင်များ",
about_modifier:"အထူးြပုြပင်သူ အေြကာင်း",
anchor_title:"ချိတ် ထည့်/ြပင်",
anchor_name:"ချိတ် အမည်",
code_title:"HTML ရင်းြမစ် ြပုြပင်ရန် ေနရာ",
code_wordwrap:"Word wrap",
colorpicker_title:"အေရာင်ေရွး",
colorpicker_picker_tab:"ေရွးေကာက်ရန်",
colorpicker_picker_title:"အေရာင်ေရွးေကာက်ရန်",
colorpicker_palette_tab:"Palette",
colorpicker_palette_title:"Palette colors",
colorpicker_named_tab:"အမည်ေပးထားေသာ",
colorpicker_named_title:"အမည်ေပးထားေသာ အေရာင်များ",
colorpicker_color:"အေရာင်:",
colorpicker_name:"အမည်:",
charmap_title:"စိတ်ြကိုက် အက္ခရာ ေရွးပါ",
image_title:"ရုပ်ပံု ထည့်/ြပင်",
image_src:"ရုပ်ပံု URL",
image_alt:"ရုပ်ပံု စာညွှန်း",
image_list:"ရုပ်ပံု စာရင်း",
image_border:"နယ်စည်း",
image_dimensions:"အတိုင်းအထွာများ",
image_vspace:"ေဒါင်လိုက် ကွက်လပ်",
image_hspace:"အလျှားလိုက် ကွက်လပ်",
image_align:"ချိန်ညိှမှု",
image_align_baseline:"ေအာက်ေြခမျဉ်း",
image_align_top:"ထိပ်",
image_align_middle:"အလယ်",
image_align_bottom:"ေအာက်ေြခ",
image_align_texttop:"ထိပ်တွင် စာသား",
image_align_textbottom:"ေအာက်ေြခတွင် စာသား",
image_align_left:"ဘယ်",
image_align_right:"ညာ",
link_title:"ချိတ်ဆက်လိပ်စာ ထည့်/ြပင်",
link_url:"ချိတ်ဆက်လိပ်စာ URL",
link_target:"Target",
link_target_same:"ချိတ်ဆက်လိပ်စာကို တူညီေသာ ဝင်းဒိုးတွင် ဖွင့်ပါ",
link_target_blank:"ချိတ်ဆက်လိပ်စာကို ဝင်းဒိုးအသစ်တွင် ဖွင့်ပါ။",
link_titlefield:"Title",
link_is_email:"သင်ြဖည့်သွင်းေသာ URL သည် email လိပ်စာနှင့်တူသည်၊ လိုအပ်ေသာ mailto: ေရှ့ဆက်စာလံုးကို ထည့်လိုပါသလား?",
link_is_external:"သင်ြဖည့်သွင်းေသာ URL သည် ြပင်ပမှ ချိတ်ဆက်လိပ်စာြဖစ်မည်၊ လိုအပ်ေသာ http:// ေရှ့ဆက်စာလံုးကို ထည့်လိုပါသလား?",
link_list:"ချိတ်ဆက်လိပ်စာ စာရင်း"
});